# Generated by Django 4.2.2 on 2023-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
